// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/unbatedfall/Documents/Github/GymLog/frontend-native/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/unbatedfall/Documents/Github/GymLog/frontend-native/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('frontend-native', appParameters);
});
require('/Users/unbatedfall/Documents/Github/GymLog/frontend-native/index.android.js');