// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gymlog/v1/gymlog.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User related messages
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Exercise related messages
type Exercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MuscleGroup   string                 `protobuf:"bytes,4,opt,name=muscle_group,json=muscleGroup,proto3" json:"muscle_group,omitempty"`
	Equipment     string                 `protobuf:"bytes,5,opt,name=equipment,proto3" json:"equipment,omitempty"`
	Difficulty    string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Instructions  []string               `protobuf:"bytes,7,rep,name=instructions,proto3" json:"instructions,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{6}
}

func (x *Exercise) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exercise) GetMuscleGroup() string {
	if x != nil {
		return x.MuscleGroup
	}
	return ""
}

func (x *Exercise) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *Exercise) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Exercise) GetInstructions() []string {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *Exercise) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Exercise) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MuscleGroup   string                 `protobuf:"bytes,3,opt,name=muscle_group,json=muscleGroup,proto3" json:"muscle_group,omitempty"`
	Equipment     string                 `protobuf:"bytes,4,opt,name=equipment,proto3" json:"equipment,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Instructions  []string               `protobuf:"bytes,6,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExerciseRequest) Reset() {
	*x = CreateExerciseRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseRequest) ProtoMessage() {}

func (x *CreateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseRequest.ProtoReflect.Descriptor instead.
func (*CreateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{7}
}

func (x *CreateExerciseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExerciseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateExerciseRequest) GetMuscleGroup() string {
	if x != nil {
		return x.MuscleGroup
	}
	return ""
}

func (x *CreateExerciseRequest) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *CreateExerciseRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateExerciseRequest) GetInstructions() []string {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type GetExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseRequest) Reset() {
	*x = GetExerciseRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseRequest) ProtoMessage() {}

func (x *GetExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{8}
}

func (x *GetExerciseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MuscleGroup   string                 `protobuf:"bytes,4,opt,name=muscle_group,json=muscleGroup,proto3" json:"muscle_group,omitempty"`
	Equipment     string                 `protobuf:"bytes,5,opt,name=equipment,proto3" json:"equipment,omitempty"`
	Difficulty    string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Instructions  []string               `protobuf:"bytes,7,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExerciseRequest) Reset() {
	*x = UpdateExerciseRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExerciseRequest) ProtoMessage() {}

func (x *UpdateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExerciseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateExerciseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExerciseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateExerciseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExerciseRequest) GetMuscleGroup() string {
	if x != nil {
		return x.MuscleGroup
	}
	return ""
}

func (x *UpdateExerciseRequest) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *UpdateExerciseRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *UpdateExerciseRequest) GetInstructions() []string {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type DeleteExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExerciseRequest) Reset() {
	*x = DeleteExerciseRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExerciseRequest) ProtoMessage() {}

func (x *DeleteExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExerciseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExerciseRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteExerciseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListExercisesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	MuscleGroup   string                 `protobuf:"bytes,3,opt,name=muscle_group,json=muscleGroup,proto3" json:"muscle_group,omitempty"` // filter by muscle group
	Equipment     string                 `protobuf:"bytes,4,opt,name=equipment,proto3" json:"equipment,omitempty"`                        // filter by equipment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExercisesRequest) Reset() {
	*x = ListExercisesRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExercisesRequest) ProtoMessage() {}

func (x *ListExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExercisesRequest.ProtoReflect.Descriptor instead.
func (*ListExercisesRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{11}
}

func (x *ListExercisesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExercisesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListExercisesRequest) GetMuscleGroup() string {
	if x != nil {
		return x.MuscleGroup
	}
	return ""
}

func (x *ListExercisesRequest) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

type ListExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*Exercise            `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExercisesResponse) Reset() {
	*x = ListExercisesResponse{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExercisesResponse) ProtoMessage() {}

func (x *ListExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExercisesResponse.ProtoReflect.Descriptor instead.
func (*ListExercisesResponse) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{12}
}

func (x *ListExercisesResponse) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *ListExercisesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Workout related messages
type WorkoutSet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Reps            int32                  `protobuf:"varint,1,opt,name=reps,proto3" json:"reps,omitempty"`
	Weight          float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	DurationSeconds float32                `protobuf:"fixed32,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Distance        float32                `protobuf:"fixed32,4,opt,name=distance,proto3" json:"distance,omitempty"`
	Notes           string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkoutSet) Reset() {
	*x = WorkoutSet{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutSet) ProtoMessage() {}

func (x *WorkoutSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutSet.ProtoReflect.Descriptor instead.
func (*WorkoutSet) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{13}
}

func (x *WorkoutSet) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *WorkoutSet) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *WorkoutSet) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *WorkoutSet) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *WorkoutSet) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type WorkoutExercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	Exercise      *Exercise              `protobuf:"bytes,2,opt,name=exercise,proto3" json:"exercise,omitempty"` // populated in responses
	Sets          []*WorkoutSet          `protobuf:"bytes,3,rep,name=sets,proto3" json:"sets,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	RestSeconds   int32                  `protobuf:"varint,5,opt,name=rest_seconds,json=restSeconds,proto3" json:"rest_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutExercise) Reset() {
	*x = WorkoutExercise{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutExercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutExercise) ProtoMessage() {}

func (x *WorkoutExercise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutExercise.ProtoReflect.Descriptor instead.
func (*WorkoutExercise) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{14}
}

func (x *WorkoutExercise) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *WorkoutExercise) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

func (x *WorkoutExercise) GetSets() []*WorkoutSet {
	if x != nil {
		return x.Sets
	}
	return nil
}

func (x *WorkoutExercise) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *WorkoutExercise) GetRestSeconds() int32 {
	if x != nil {
		return x.RestSeconds
	}
	return 0
}

type Workout struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Exercises       []*WorkoutExercise     `protobuf:"bytes,5,rep,name=exercises,proto3" json:"exercises,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Notes           string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Workout) Reset() {
	*x = Workout{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workout) ProtoMessage() {}

func (x *Workout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workout.ProtoReflect.Descriptor instead.
func (*Workout) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{15}
}

func (x *Workout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workout) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Workout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workout) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workout) GetExercises() []*WorkoutExercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *Workout) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Workout) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Workout) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Workout) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Workout) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workout) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Exercises     []*WorkoutExercise     `protobuf:"bytes,4,rep,name=exercises,proto3" json:"exercises,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkoutRequest) Reset() {
	*x = CreateWorkoutRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkoutRequest) ProtoMessage() {}

func (x *CreateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{16}
}

func (x *CreateWorkoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWorkoutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkoutRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkoutRequest) GetExercises() []*WorkoutExercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *CreateWorkoutRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CreateWorkoutRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type GetWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutRequest) Reset() {
	*x = GetWorkoutRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutRequest) ProtoMessage() {}

func (x *GetWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutRequest.ProtoReflect.Descriptor instead.
func (*GetWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{17}
}

func (x *GetWorkoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateWorkoutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Exercises       []*WorkoutExercise     `protobuf:"bytes,4,rep,name=exercises,proto3" json:"exercises,omitempty"`
	FinishedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Notes           string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateWorkoutRequest) Reset() {
	*x = UpdateWorkoutRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkoutRequest) ProtoMessage() {}

func (x *UpdateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateWorkoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetExercises() []*WorkoutExercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *UpdateWorkoutRequest) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *UpdateWorkoutRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *UpdateWorkoutRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type DeleteWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkoutRequest) Reset() {
	*x = DeleteWorkoutRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkoutRequest) ProtoMessage() {}

func (x *DeleteWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkoutRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteWorkoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWorkoutsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkoutsRequest) Reset() {
	*x = ListWorkoutsRequest{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkoutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkoutsRequest) ProtoMessage() {}

func (x *ListWorkoutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkoutsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkoutsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{20}
}

func (x *ListWorkoutsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListWorkoutsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkoutsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListWorkoutsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ListWorkoutsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ListWorkoutsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workouts      []*Workout             `protobuf:"bytes,1,rep,name=workouts,proto3" json:"workouts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkoutsResponse) Reset() {
	*x = ListWorkoutsResponse{}
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkoutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkoutsResponse) ProtoMessage() {}

func (x *ListWorkoutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gymlog_v1_gymlog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkoutsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkoutsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gymlog_v1_gymlog_proto_rawDescGZIP(), []int{21}
}

func (x *ListWorkoutsResponse) GetWorkouts() []*Workout {
	if x != nil {
		return x.Workouts
	}
	return nil
}

func (x *ListWorkoutsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_proto_gymlog_v1_gymlog_proto protoreflect.FileDescriptor

const file_proto_gymlog_v1_gymlog_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/gymlog/v1/gymlog.proto\x12\tgymlog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfa\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9d\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x91\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\"N\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"b\n" +
	"\x11ListUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.gymlog.v1.UserR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xcb\x02\n" +
	"\bExercise\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fmuscle_group\x18\x04 \x01(\tR\vmuscleGroup\x12\x1c\n" +
	"\tequipment\x18\x05 \x01(\tR\tequipment\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tR\n" +
	"difficulty\x12\"\n" +
	"\finstructions\x18\a \x03(\tR\finstructions\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd2\x01\n" +
	"\x15CreateExerciseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fmuscle_group\x18\x03 \x01(\tR\vmuscleGroup\x12\x1c\n" +
	"\tequipment\x18\x04 \x01(\tR\tequipment\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\"\n" +
	"\finstructions\x18\x06 \x03(\tR\finstructions\"$\n" +
	"\x12GetExerciseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe2\x01\n" +
	"\x15UpdateExerciseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fmuscle_group\x18\x04 \x01(\tR\vmuscleGroup\x12\x1c\n" +
	"\tequipment\x18\x05 \x01(\tR\tequipment\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tR\n" +
	"difficulty\x12\"\n" +
	"\finstructions\x18\a \x03(\tR\finstructions\"'\n" +
	"\x15DeleteExerciseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x93\x01\n" +
	"\x14ListExercisesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12!\n" +
	"\fmuscle_group\x18\x03 \x01(\tR\vmuscleGroup\x12\x1c\n" +
	"\tequipment\x18\x04 \x01(\tR\tequipment\"r\n" +
	"\x15ListExercisesResponse\x121\n" +
	"\texercises\x18\x01 \x03(\v2\x13.gymlog.v1.ExerciseR\texercises\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x95\x01\n" +
	"\n" +
	"WorkoutSet\x12\x12\n" +
	"\x04reps\x18\x01 \x01(\x05R\x04reps\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x02R\x0fdurationSeconds\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x02R\bdistance\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\xc7\x01\n" +
	"\x0fWorkoutExercise\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12/\n" +
	"\bexercise\x18\x02 \x01(\v2\x13.gymlog.v1.ExerciseR\bexercise\x12)\n" +
	"\x04sets\x18\x03 \x03(\v2\x15.gymlog.v1.WorkoutSetR\x04sets\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\x12!\n" +
	"\frest_seconds\x18\x05 \x01(\x05R\vrestSeconds\"\xd1\x03\n" +
	"\aWorkout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x128\n" +
	"\texercises\x18\x05 \x03(\v2\x1a.gymlog.v1.WorkoutExerciseR\texercises\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x05R\x0fdurationSeconds\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf0\x01\n" +
	"\x14CreateWorkoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\texercises\x18\x04 \x03(\v2\x1a.gymlog.v1.WorkoutExerciseR\texercises\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"#\n" +
	"\x11GetWorkoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x94\x02\n" +
	"\x14UpdateWorkoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\texercises\x18\x04 \x03(\v2\x1a.gymlog.v1.WorkoutExerciseR\texercises\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x05R\x0fdurationSeconds\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"&\n" +
	"\x14DeleteWorkoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdc\x01\n" +
	"\x13ListWorkoutsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"n\n" +
	"\x14ListWorkoutsResponse\x12.\n" +
	"\bworkouts\x18\x01 \x03(\v2\x12.gymlog.v1.WorkoutR\bworkouts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x86\x02\n" +
	"\vUserService\x12;\n" +
	"\n" +
	"CreateUser\x12\x1c.gymlog.v1.CreateUserRequest\x1a\x0f.gymlog.v1.User\x125\n" +
	"\aGetUser\x12\x19.gymlog.v1.GetUserRequest\x1a\x0f.gymlog.v1.User\x12;\n" +
	"\n" +
	"UpdateUser\x12\x1c.gymlog.v1.UpdateUserRequest\x1a\x0f.gymlog.v1.User\x12F\n" +
	"\tListUsers\x12\x1b.gymlog.v1.ListUsersRequest\x1a\x1c.gymlog.v1.ListUsersResponse2\x86\x03\n" +
	"\x0fExerciseService\x12G\n" +
	"\x0eCreateExercise\x12 .gymlog.v1.CreateExerciseRequest\x1a\x13.gymlog.v1.Exercise\x12A\n" +
	"\vGetExercise\x12\x1d.gymlog.v1.GetExerciseRequest\x1a\x13.gymlog.v1.Exercise\x12G\n" +
	"\x0eUpdateExercise\x12 .gymlog.v1.UpdateExerciseRequest\x1a\x13.gymlog.v1.Exercise\x12J\n" +
	"\x0eDeleteExercise\x12 .gymlog.v1.DeleteExerciseRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\rListExercises\x12\x1f.gymlog.v1.ListExercisesRequest\x1a .gymlog.v1.ListExercisesResponse2\xf7\x02\n" +
	"\x0eWorkoutService\x12D\n" +
	"\rCreateWorkout\x12\x1f.gymlog.v1.CreateWorkoutRequest\x1a\x12.gymlog.v1.Workout\x12>\n" +
	"\n" +
	"GetWorkout\x12\x1c.gymlog.v1.GetWorkoutRequest\x1a\x12.gymlog.v1.Workout\x12D\n" +
	"\rUpdateWorkout\x12\x1f.gymlog.v1.UpdateWorkoutRequest\x1a\x12.gymlog.v1.Workout\x12H\n" +
	"\rDeleteWorkout\x12\x1f.gymlog.v1.DeleteWorkoutRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\fListWorkouts\x12\x1e.gymlog.v1.ListWorkoutsRequest\x1a\x1f.gymlog.v1.ListWorkoutsResponseB&Z$github.com/gymlog/backend/pkg/api/v1b\x06proto3"

var (
	file_proto_gymlog_v1_gymlog_proto_rawDescOnce sync.Once
	file_proto_gymlog_v1_gymlog_proto_rawDescData []byte
)

func file_proto_gymlog_v1_gymlog_proto_rawDescGZIP() []byte {
	file_proto_gymlog_v1_gymlog_proto_rawDescOnce.Do(func() {
		file_proto_gymlog_v1_gymlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gymlog_v1_gymlog_proto_rawDesc), len(file_proto_gymlog_v1_gymlog_proto_rawDesc)))
	})
	return file_proto_gymlog_v1_gymlog_proto_rawDescData
}

var file_proto_gymlog_v1_gymlog_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_gymlog_v1_gymlog_proto_goTypes = []any{
	(*User)(nil),                  // 0: gymlog.v1.User
	(*CreateUserRequest)(nil),     // 1: gymlog.v1.CreateUserRequest
	(*GetUserRequest)(nil),        // 2: gymlog.v1.GetUserRequest
	(*UpdateUserRequest)(nil),     // 3: gymlog.v1.UpdateUserRequest
	(*ListUsersRequest)(nil),      // 4: gymlog.v1.ListUsersRequest
	(*ListUsersResponse)(nil),     // 5: gymlog.v1.ListUsersResponse
	(*Exercise)(nil),              // 6: gymlog.v1.Exercise
	(*CreateExerciseRequest)(nil), // 7: gymlog.v1.CreateExerciseRequest
	(*GetExerciseRequest)(nil),    // 8: gymlog.v1.GetExerciseRequest
	(*UpdateExerciseRequest)(nil), // 9: gymlog.v1.UpdateExerciseRequest
	(*DeleteExerciseRequest)(nil), // 10: gymlog.v1.DeleteExerciseRequest
	(*ListExercisesRequest)(nil),  // 11: gymlog.v1.ListExercisesRequest
	(*ListExercisesResponse)(nil), // 12: gymlog.v1.ListExercisesResponse
	(*WorkoutSet)(nil),            // 13: gymlog.v1.WorkoutSet
	(*WorkoutExercise)(nil),       // 14: gymlog.v1.WorkoutExercise
	(*Workout)(nil),               // 15: gymlog.v1.Workout
	(*CreateWorkoutRequest)(nil),  // 16: gymlog.v1.CreateWorkoutRequest
	(*GetWorkoutRequest)(nil),     // 17: gymlog.v1.GetWorkoutRequest
	(*UpdateWorkoutRequest)(nil),  // 18: gymlog.v1.UpdateWorkoutRequest
	(*DeleteWorkoutRequest)(nil),  // 19: gymlog.v1.DeleteWorkoutRequest
	(*ListWorkoutsRequest)(nil),   // 20: gymlog.v1.ListWorkoutsRequest
	(*ListWorkoutsResponse)(nil),  // 21: gymlog.v1.ListWorkoutsResponse
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 23: google.protobuf.Empty
}
var file_proto_gymlog_v1_gymlog_proto_depIdxs = []int32{
	22, // 0: gymlog.v1.User.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: gymlog.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: gymlog.v1.ListUsersResponse.users:type_name -> gymlog.v1.User
	22, // 3: gymlog.v1.Exercise.created_at:type_name -> google.protobuf.Timestamp
	22, // 4: gymlog.v1.Exercise.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: gymlog.v1.ListExercisesResponse.exercises:type_name -> gymlog.v1.Exercise
	6,  // 6: gymlog.v1.WorkoutExercise.exercise:type_name -> gymlog.v1.Exercise
	13, // 7: gymlog.v1.WorkoutExercise.sets:type_name -> gymlog.v1.WorkoutSet
	14, // 8: gymlog.v1.Workout.exercises:type_name -> gymlog.v1.WorkoutExercise
	22, // 9: gymlog.v1.Workout.started_at:type_name -> google.protobuf.Timestamp
	22, // 10: gymlog.v1.Workout.finished_at:type_name -> google.protobuf.Timestamp
	22, // 11: gymlog.v1.Workout.created_at:type_name -> google.protobuf.Timestamp
	22, // 12: gymlog.v1.Workout.updated_at:type_name -> google.protobuf.Timestamp
	14, // 13: gymlog.v1.CreateWorkoutRequest.exercises:type_name -> gymlog.v1.WorkoutExercise
	22, // 14: gymlog.v1.CreateWorkoutRequest.started_at:type_name -> google.protobuf.Timestamp
	14, // 15: gymlog.v1.UpdateWorkoutRequest.exercises:type_name -> gymlog.v1.WorkoutExercise
	22, // 16: gymlog.v1.UpdateWorkoutRequest.finished_at:type_name -> google.protobuf.Timestamp
	22, // 17: gymlog.v1.ListWorkoutsRequest.start_date:type_name -> google.protobuf.Timestamp
	22, // 18: gymlog.v1.ListWorkoutsRequest.end_date:type_name -> google.protobuf.Timestamp
	15, // 19: gymlog.v1.ListWorkoutsResponse.workouts:type_name -> gymlog.v1.Workout
	1,  // 20: gymlog.v1.UserService.CreateUser:input_type -> gymlog.v1.CreateUserRequest
	2,  // 21: gymlog.v1.UserService.GetUser:input_type -> gymlog.v1.GetUserRequest
	3,  // 22: gymlog.v1.UserService.UpdateUser:input_type -> gymlog.v1.UpdateUserRequest
	4,  // 23: gymlog.v1.UserService.ListUsers:input_type -> gymlog.v1.ListUsersRequest
	7,  // 24: gymlog.v1.ExerciseService.CreateExercise:input_type -> gymlog.v1.CreateExerciseRequest
	8,  // 25: gymlog.v1.ExerciseService.GetExercise:input_type -> gymlog.v1.GetExerciseRequest
	9,  // 26: gymlog.v1.ExerciseService.UpdateExercise:input_type -> gymlog.v1.UpdateExerciseRequest
	10, // 27: gymlog.v1.ExerciseService.DeleteExercise:input_type -> gymlog.v1.DeleteExerciseRequest
	11, // 28: gymlog.v1.ExerciseService.ListExercises:input_type -> gymlog.v1.ListExercisesRequest
	16, // 29: gymlog.v1.WorkoutService.CreateWorkout:input_type -> gymlog.v1.CreateWorkoutRequest
	17, // 30: gymlog.v1.WorkoutService.GetWorkout:input_type -> gymlog.v1.GetWorkoutRequest
	18, // 31: gymlog.v1.WorkoutService.UpdateWorkout:input_type -> gymlog.v1.UpdateWorkoutRequest
	19, // 32: gymlog.v1.WorkoutService.DeleteWorkout:input_type -> gymlog.v1.DeleteWorkoutRequest
	20, // 33: gymlog.v1.WorkoutService.ListWorkouts:input_type -> gymlog.v1.ListWorkoutsRequest
	0,  // 34: gymlog.v1.UserService.CreateUser:output_type -> gymlog.v1.User
	0,  // 35: gymlog.v1.UserService.GetUser:output_type -> gymlog.v1.User
	0,  // 36: gymlog.v1.UserService.UpdateUser:output_type -> gymlog.v1.User
	5,  // 37: gymlog.v1.UserService.ListUsers:output_type -> gymlog.v1.ListUsersResponse
	6,  // 38: gymlog.v1.ExerciseService.CreateExercise:output_type -> gymlog.v1.Exercise
	6,  // 39: gymlog.v1.ExerciseService.GetExercise:output_type -> gymlog.v1.Exercise
	6,  // 40: gymlog.v1.ExerciseService.UpdateExercise:output_type -> gymlog.v1.Exercise
	23, // 41: gymlog.v1.ExerciseService.DeleteExercise:output_type -> google.protobuf.Empty
	12, // 42: gymlog.v1.ExerciseService.ListExercises:output_type -> gymlog.v1.ListExercisesResponse
	15, // 43: gymlog.v1.WorkoutService.CreateWorkout:output_type -> gymlog.v1.Workout
	15, // 44: gymlog.v1.WorkoutService.GetWorkout:output_type -> gymlog.v1.Workout
	15, // 45: gymlog.v1.WorkoutService.UpdateWorkout:output_type -> gymlog.v1.Workout
	23, // 46: gymlog.v1.WorkoutService.DeleteWorkout:output_type -> google.protobuf.Empty
	21, // 47: gymlog.v1.WorkoutService.ListWorkouts:output_type -> gymlog.v1.ListWorkoutsResponse
	34, // [34:48] is the sub-list for method output_type
	20, // [20:34] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_gymlog_v1_gymlog_proto_init() }
func file_proto_gymlog_v1_gymlog_proto_init() {
	if File_proto_gymlog_v1_gymlog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gymlog_v1_gymlog_proto_rawDesc), len(file_proto_gymlog_v1_gymlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_gymlog_v1_gymlog_proto_goTypes,
		DependencyIndexes: file_proto_gymlog_v1_gymlog_proto_depIdxs,
		MessageInfos:      file_proto_gymlog_v1_gymlog_proto_msgTypes,
	}.Build()
	File_proto_gymlog_v1_gymlog_proto = out.File
	file_proto_gymlog_v1_gymlog_proto_goTypes = nil
	file_proto_gymlog_v1_gymlog_proto_depIdxs = nil
}
