// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: gymlog/v1/gymlog.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateUser_FullMethodName = "/gymlog.v1.UserService/CreateUser"
	UserService_GetUser_FullMethodName    = "/gymlog.v1.UserService/GetUser"
	UserService_UpdateUser_FullMethodName = "/gymlog.v1.UserService/UpdateUser"
	UserService_ListUsers_FullMethodName  = "/gymlog.v1.UserService/ListUsers"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Services
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, UserService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// Services
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gymlog.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gymlog/v1/gymlog.proto",
}

const (
	ExerciseService_CreateExercise_FullMethodName = "/gymlog.v1.ExerciseService/CreateExercise"
	ExerciseService_GetExercise_FullMethodName    = "/gymlog.v1.ExerciseService/GetExercise"
	ExerciseService_UpdateExercise_FullMethodName = "/gymlog.v1.ExerciseService/UpdateExercise"
	ExerciseService_DeleteExercise_FullMethodName = "/gymlog.v1.ExerciseService/DeleteExercise"
	ExerciseService_ListExercises_FullMethodName  = "/gymlog.v1.ExerciseService/ListExercises"
)

// ExerciseServiceClient is the client API for ExerciseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExerciseServiceClient interface {
	CreateExercise(ctx context.Context, in *CreateExerciseRequest, opts ...grpc.CallOption) (*Exercise, error)
	GetExercise(ctx context.Context, in *GetExerciseRequest, opts ...grpc.CallOption) (*Exercise, error)
	UpdateExercise(ctx context.Context, in *UpdateExerciseRequest, opts ...grpc.CallOption) (*Exercise, error)
	DeleteExercise(ctx context.Context, in *DeleteExerciseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListExercises(ctx context.Context, in *ListExercisesRequest, opts ...grpc.CallOption) (*ListExercisesResponse, error)
}

type exerciseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExerciseServiceClient(cc grpc.ClientConnInterface) ExerciseServiceClient {
	return &exerciseServiceClient{cc}
}

func (c *exerciseServiceClient) CreateExercise(ctx context.Context, in *CreateExerciseRequest, opts ...grpc.CallOption) (*Exercise, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exercise)
	err := c.cc.Invoke(ctx, ExerciseService_CreateExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetExercise(ctx context.Context, in *GetExerciseRequest, opts ...grpc.CallOption) (*Exercise, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exercise)
	err := c.cc.Invoke(ctx, ExerciseService_GetExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) UpdateExercise(ctx context.Context, in *UpdateExerciseRequest, opts ...grpc.CallOption) (*Exercise, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exercise)
	err := c.cc.Invoke(ctx, ExerciseService_UpdateExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) DeleteExercise(ctx context.Context, in *DeleteExerciseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ExerciseService_DeleteExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) ListExercises(ctx context.Context, in *ListExercisesRequest, opts ...grpc.CallOption) (*ListExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExercisesResponse)
	err := c.cc.Invoke(ctx, ExerciseService_ListExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExerciseServiceServer is the server API for ExerciseService service.
// All implementations must embed UnimplementedExerciseServiceServer
// for forward compatibility.
type ExerciseServiceServer interface {
	CreateExercise(context.Context, *CreateExerciseRequest) (*Exercise, error)
	GetExercise(context.Context, *GetExerciseRequest) (*Exercise, error)
	UpdateExercise(context.Context, *UpdateExerciseRequest) (*Exercise, error)
	DeleteExercise(context.Context, *DeleteExerciseRequest) (*emptypb.Empty, error)
	ListExercises(context.Context, *ListExercisesRequest) (*ListExercisesResponse, error)
	mustEmbedUnimplementedExerciseServiceServer()
}

// UnimplementedExerciseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExerciseServiceServer struct{}

func (UnimplementedExerciseServiceServer) CreateExercise(context.Context, *CreateExerciseRequest) (*Exercise, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExercise not implemented")
}
func (UnimplementedExerciseServiceServer) GetExercise(context.Context, *GetExerciseRequest) (*Exercise, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExercise not implemented")
}
func (UnimplementedExerciseServiceServer) UpdateExercise(context.Context, *UpdateExerciseRequest) (*Exercise, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExercise not implemented")
}
func (UnimplementedExerciseServiceServer) DeleteExercise(context.Context, *DeleteExerciseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExercise not implemented")
}
func (UnimplementedExerciseServiceServer) ListExercises(context.Context, *ListExercisesRequest) (*ListExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExercises not implemented")
}
func (UnimplementedExerciseServiceServer) mustEmbedUnimplementedExerciseServiceServer() {}
func (UnimplementedExerciseServiceServer) testEmbeddedByValue()                         {}

// UnsafeExerciseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExerciseServiceServer will
// result in compilation errors.
type UnsafeExerciseServiceServer interface {
	mustEmbedUnimplementedExerciseServiceServer()
}

func RegisterExerciseServiceServer(s grpc.ServiceRegistrar, srv ExerciseServiceServer) {
	// If the following call pancis, it indicates UnimplementedExerciseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExerciseService_ServiceDesc, srv)
}

func _ExerciseService_CreateExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).CreateExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_CreateExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).CreateExercise(ctx, req.(*CreateExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExercise(ctx, req.(*GetExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_UpdateExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).UpdateExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_UpdateExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).UpdateExercise(ctx, req.(*UpdateExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_DeleteExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).DeleteExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_DeleteExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).DeleteExercise(ctx, req.(*DeleteExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_ListExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).ListExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_ListExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).ListExercises(ctx, req.(*ListExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExerciseService_ServiceDesc is the grpc.ServiceDesc for ExerciseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExerciseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gymlog.v1.ExerciseService",
	HandlerType: (*ExerciseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExercise",
			Handler:    _ExerciseService_CreateExercise_Handler,
		},
		{
			MethodName: "GetExercise",
			Handler:    _ExerciseService_GetExercise_Handler,
		},
		{
			MethodName: "UpdateExercise",
			Handler:    _ExerciseService_UpdateExercise_Handler,
		},
		{
			MethodName: "DeleteExercise",
			Handler:    _ExerciseService_DeleteExercise_Handler,
		},
		{
			MethodName: "ListExercises",
			Handler:    _ExerciseService_ListExercises_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gymlog/v1/gymlog.proto",
}

const (
	WorkoutService_CreateWorkout_FullMethodName = "/gymlog.v1.WorkoutService/CreateWorkout"
	WorkoutService_GetWorkout_FullMethodName    = "/gymlog.v1.WorkoutService/GetWorkout"
	WorkoutService_UpdateWorkout_FullMethodName = "/gymlog.v1.WorkoutService/UpdateWorkout"
	WorkoutService_DeleteWorkout_FullMethodName = "/gymlog.v1.WorkoutService/DeleteWorkout"
	WorkoutService_ListWorkouts_FullMethodName  = "/gymlog.v1.WorkoutService/ListWorkouts"
)

// WorkoutServiceClient is the client API for WorkoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutServiceClient interface {
	CreateWorkout(ctx context.Context, in *CreateWorkoutRequest, opts ...grpc.CallOption) (*Workout, error)
	GetWorkout(ctx context.Context, in *GetWorkoutRequest, opts ...grpc.CallOption) (*Workout, error)
	UpdateWorkout(ctx context.Context, in *UpdateWorkoutRequest, opts ...grpc.CallOption) (*Workout, error)
	DeleteWorkout(ctx context.Context, in *DeleteWorkoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListWorkouts(ctx context.Context, in *ListWorkoutsRequest, opts ...grpc.CallOption) (*ListWorkoutsResponse, error)
}

type workoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutServiceClient(cc grpc.ClientConnInterface) WorkoutServiceClient {
	return &workoutServiceClient{cc}
}

func (c *workoutServiceClient) CreateWorkout(ctx context.Context, in *CreateWorkoutRequest, opts ...grpc.CallOption) (*Workout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workout)
	err := c.cc.Invoke(ctx, WorkoutService_CreateWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkout(ctx context.Context, in *GetWorkoutRequest, opts ...grpc.CallOption) (*Workout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workout)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) UpdateWorkout(ctx context.Context, in *UpdateWorkoutRequest, opts ...grpc.CallOption) (*Workout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workout)
	err := c.cc.Invoke(ctx, WorkoutService_UpdateWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) DeleteWorkout(ctx context.Context, in *DeleteWorkoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutService_DeleteWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) ListWorkouts(ctx context.Context, in *ListWorkoutsRequest, opts ...grpc.CallOption) (*ListWorkoutsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkoutsResponse)
	err := c.cc.Invoke(ctx, WorkoutService_ListWorkouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutServiceServer is the server API for WorkoutService service.
// All implementations must embed UnimplementedWorkoutServiceServer
// for forward compatibility.
type WorkoutServiceServer interface {
	CreateWorkout(context.Context, *CreateWorkoutRequest) (*Workout, error)
	GetWorkout(context.Context, *GetWorkoutRequest) (*Workout, error)
	UpdateWorkout(context.Context, *UpdateWorkoutRequest) (*Workout, error)
	DeleteWorkout(context.Context, *DeleteWorkoutRequest) (*emptypb.Empty, error)
	ListWorkouts(context.Context, *ListWorkoutsRequest) (*ListWorkoutsResponse, error)
	mustEmbedUnimplementedWorkoutServiceServer()
}

// UnimplementedWorkoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutServiceServer struct{}

func (UnimplementedWorkoutServiceServer) CreateWorkout(context.Context, *CreateWorkoutRequest) (*Workout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkout(context.Context, *GetWorkoutRequest) (*Workout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) UpdateWorkout(context.Context, *UpdateWorkoutRequest) (*Workout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) DeleteWorkout(context.Context, *DeleteWorkoutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) ListWorkouts(context.Context, *ListWorkoutsRequest) (*ListWorkoutsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkouts not implemented")
}
func (UnimplementedWorkoutServiceServer) mustEmbedUnimplementedWorkoutServiceServer() {}
func (UnimplementedWorkoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutServiceServer will
// result in compilation errors.
type UnsafeWorkoutServiceServer interface {
	mustEmbedUnimplementedWorkoutServiceServer()
}

func RegisterWorkoutServiceServer(s grpc.ServiceRegistrar, srv WorkoutServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutService_ServiceDesc, srv)
}

func _WorkoutService_CreateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).CreateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_CreateWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).CreateWorkout(ctx, req.(*CreateWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkout(ctx, req.(*GetWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_UpdateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).UpdateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_UpdateWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).UpdateWorkout(ctx, req.(*UpdateWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_DeleteWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).DeleteWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_DeleteWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).DeleteWorkout(ctx, req.(*DeleteWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_ListWorkouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).ListWorkouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_ListWorkouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).ListWorkouts(ctx, req.(*ListWorkoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutService_ServiceDesc is the grpc.ServiceDesc for WorkoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gymlog.v1.WorkoutService",
	HandlerType: (*WorkoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkout",
			Handler:    _WorkoutService_CreateWorkout_Handler,
		},
		{
			MethodName: "GetWorkout",
			Handler:    _WorkoutService_GetWorkout_Handler,
		},
		{
			MethodName: "UpdateWorkout",
			Handler:    _WorkoutService_UpdateWorkout_Handler,
		},
		{
			MethodName: "DeleteWorkout",
			Handler:    _WorkoutService_DeleteWorkout_Handler,
		},
		{
			MethodName: "ListWorkouts",
			Handler:    _WorkoutService_ListWorkouts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gymlog/v1/gymlog.proto",
}

const (
	WorkoutSessionService_CreateWorkoutSession_FullMethodName = "/gymlog.v1.WorkoutSessionService/CreateWorkoutSession"
	WorkoutSessionService_GetWorkoutSession_FullMethodName    = "/gymlog.v1.WorkoutSessionService/GetWorkoutSession"
	WorkoutSessionService_UpdateWorkoutSession_FullMethodName = "/gymlog.v1.WorkoutSessionService/UpdateWorkoutSession"
	WorkoutSessionService_DeleteWorkoutSession_FullMethodName = "/gymlog.v1.WorkoutSessionService/DeleteWorkoutSession"
	WorkoutSessionService_ListWorkoutSessions_FullMethodName  = "/gymlog.v1.WorkoutSessionService/ListWorkoutSessions"
	WorkoutSessionService_StartExercise_FullMethodName        = "/gymlog.v1.WorkoutSessionService/StartExercise"
	WorkoutSessionService_FinishExercise_FullMethodName       = "/gymlog.v1.WorkoutSessionService/FinishExercise"
	WorkoutSessionService_UpdateSet_FullMethodName            = "/gymlog.v1.WorkoutSessionService/UpdateSet"
)

// WorkoutSessionServiceClient is the client API for WorkoutSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutSessionServiceClient interface {
	CreateWorkoutSession(ctx context.Context, in *CreateWorkoutSessionRequest, opts ...grpc.CallOption) (*WorkoutSession, error)
	GetWorkoutSession(ctx context.Context, in *GetWorkoutSessionRequest, opts ...grpc.CallOption) (*WorkoutSession, error)
	UpdateWorkoutSession(ctx context.Context, in *UpdateWorkoutSessionRequest, opts ...grpc.CallOption) (*WorkoutSession, error)
	DeleteWorkoutSession(ctx context.Context, in *DeleteWorkoutSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListWorkoutSessions(ctx context.Context, in *ListWorkoutSessionsRequest, opts ...grpc.CallOption) (*ListWorkoutSessionsResponse, error)
	StartExercise(ctx context.Context, in *StartExerciseRequest, opts ...grpc.CallOption) (*WorkoutSession, error)
	FinishExercise(ctx context.Context, in *FinishExerciseRequest, opts ...grpc.CallOption) (*WorkoutSession, error)
	UpdateSet(ctx context.Context, in *UpdateSetRequest, opts ...grpc.CallOption) (*WorkoutSession, error)
}

type workoutSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutSessionServiceClient(cc grpc.ClientConnInterface) WorkoutSessionServiceClient {
	return &workoutSessionServiceClient{cc}
}

func (c *workoutSessionServiceClient) CreateWorkoutSession(ctx context.Context, in *CreateWorkoutSessionRequest, opts ...grpc.CallOption) (*WorkoutSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutSession)
	err := c.cc.Invoke(ctx, WorkoutSessionService_CreateWorkoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutSessionServiceClient) GetWorkoutSession(ctx context.Context, in *GetWorkoutSessionRequest, opts ...grpc.CallOption) (*WorkoutSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutSession)
	err := c.cc.Invoke(ctx, WorkoutSessionService_GetWorkoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutSessionServiceClient) UpdateWorkoutSession(ctx context.Context, in *UpdateWorkoutSessionRequest, opts ...grpc.CallOption) (*WorkoutSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutSession)
	err := c.cc.Invoke(ctx, WorkoutSessionService_UpdateWorkoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutSessionServiceClient) DeleteWorkoutSession(ctx context.Context, in *DeleteWorkoutSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkoutSessionService_DeleteWorkoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutSessionServiceClient) ListWorkoutSessions(ctx context.Context, in *ListWorkoutSessionsRequest, opts ...grpc.CallOption) (*ListWorkoutSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkoutSessionsResponse)
	err := c.cc.Invoke(ctx, WorkoutSessionService_ListWorkoutSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutSessionServiceClient) StartExercise(ctx context.Context, in *StartExerciseRequest, opts ...grpc.CallOption) (*WorkoutSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutSession)
	err := c.cc.Invoke(ctx, WorkoutSessionService_StartExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutSessionServiceClient) FinishExercise(ctx context.Context, in *FinishExerciseRequest, opts ...grpc.CallOption) (*WorkoutSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutSession)
	err := c.cc.Invoke(ctx, WorkoutSessionService_FinishExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutSessionServiceClient) UpdateSet(ctx context.Context, in *UpdateSetRequest, opts ...grpc.CallOption) (*WorkoutSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutSession)
	err := c.cc.Invoke(ctx, WorkoutSessionService_UpdateSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutSessionServiceServer is the server API for WorkoutSessionService service.
// All implementations must embed UnimplementedWorkoutSessionServiceServer
// for forward compatibility.
type WorkoutSessionServiceServer interface {
	CreateWorkoutSession(context.Context, *CreateWorkoutSessionRequest) (*WorkoutSession, error)
	GetWorkoutSession(context.Context, *GetWorkoutSessionRequest) (*WorkoutSession, error)
	UpdateWorkoutSession(context.Context, *UpdateWorkoutSessionRequest) (*WorkoutSession, error)
	DeleteWorkoutSession(context.Context, *DeleteWorkoutSessionRequest) (*emptypb.Empty, error)
	ListWorkoutSessions(context.Context, *ListWorkoutSessionsRequest) (*ListWorkoutSessionsResponse, error)
	StartExercise(context.Context, *StartExerciseRequest) (*WorkoutSession, error)
	FinishExercise(context.Context, *FinishExerciseRequest) (*WorkoutSession, error)
	UpdateSet(context.Context, *UpdateSetRequest) (*WorkoutSession, error)
	mustEmbedUnimplementedWorkoutSessionServiceServer()
}

// UnimplementedWorkoutSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutSessionServiceServer struct{}

func (UnimplementedWorkoutSessionServiceServer) CreateWorkoutSession(context.Context, *CreateWorkoutSessionRequest) (*WorkoutSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkoutSession not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) GetWorkoutSession(context.Context, *GetWorkoutSessionRequest) (*WorkoutSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkoutSession not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) UpdateWorkoutSession(context.Context, *UpdateWorkoutSessionRequest) (*WorkoutSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkoutSession not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) DeleteWorkoutSession(context.Context, *DeleteWorkoutSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkoutSession not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) ListWorkoutSessions(context.Context, *ListWorkoutSessionsRequest) (*ListWorkoutSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkoutSessions not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) StartExercise(context.Context, *StartExerciseRequest) (*WorkoutSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartExercise not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) FinishExercise(context.Context, *FinishExerciseRequest) (*WorkoutSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishExercise not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) UpdateSet(context.Context, *UpdateSetRequest) (*WorkoutSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSet not implemented")
}
func (UnimplementedWorkoutSessionServiceServer) mustEmbedUnimplementedWorkoutSessionServiceServer() {}
func (UnimplementedWorkoutSessionServiceServer) testEmbeddedByValue()                               {}

// UnsafeWorkoutSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutSessionServiceServer will
// result in compilation errors.
type UnsafeWorkoutSessionServiceServer interface {
	mustEmbedUnimplementedWorkoutSessionServiceServer()
}

func RegisterWorkoutSessionServiceServer(s grpc.ServiceRegistrar, srv WorkoutSessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkoutSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutSessionService_ServiceDesc, srv)
}

func _WorkoutSessionService_CreateWorkoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).CreateWorkoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_CreateWorkoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).CreateWorkoutSession(ctx, req.(*CreateWorkoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutSessionService_GetWorkoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).GetWorkoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_GetWorkoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).GetWorkoutSession(ctx, req.(*GetWorkoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutSessionService_UpdateWorkoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).UpdateWorkoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_UpdateWorkoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).UpdateWorkoutSession(ctx, req.(*UpdateWorkoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutSessionService_DeleteWorkoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).DeleteWorkoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_DeleteWorkoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).DeleteWorkoutSession(ctx, req.(*DeleteWorkoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutSessionService_ListWorkoutSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkoutSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).ListWorkoutSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_ListWorkoutSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).ListWorkoutSessions(ctx, req.(*ListWorkoutSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutSessionService_StartExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).StartExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_StartExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).StartExercise(ctx, req.(*StartExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutSessionService_FinishExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).FinishExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_FinishExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).FinishExercise(ctx, req.(*FinishExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutSessionService_UpdateSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutSessionServiceServer).UpdateSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutSessionService_UpdateSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutSessionServiceServer).UpdateSet(ctx, req.(*UpdateSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutSessionService_ServiceDesc is the grpc.ServiceDesc for WorkoutSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gymlog.v1.WorkoutSessionService",
	HandlerType: (*WorkoutSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkoutSession",
			Handler:    _WorkoutSessionService_CreateWorkoutSession_Handler,
		},
		{
			MethodName: "GetWorkoutSession",
			Handler:    _WorkoutSessionService_GetWorkoutSession_Handler,
		},
		{
			MethodName: "UpdateWorkoutSession",
			Handler:    _WorkoutSessionService_UpdateWorkoutSession_Handler,
		},
		{
			MethodName: "DeleteWorkoutSession",
			Handler:    _WorkoutSessionService_DeleteWorkoutSession_Handler,
		},
		{
			MethodName: "ListWorkoutSessions",
			Handler:    _WorkoutSessionService_ListWorkoutSessions_Handler,
		},
		{
			MethodName: "StartExercise",
			Handler:    _WorkoutSessionService_StartExercise_Handler,
		},
		{
			MethodName: "FinishExercise",
			Handler:    _WorkoutSessionService_FinishExercise_Handler,
		},
		{
			MethodName: "UpdateSet",
			Handler:    _WorkoutSessionService_UpdateSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gymlog/v1/gymlog.proto",
}
